version: '3.8'

services:
  flutter-app:
    build: .
    container_name: flutter_app_container
    volumes:
      - .:/app
      - /app/build
    ports:
      - "8080:8080"
    command: bash -c "flutter pub get && flutter run -d web-server --web-port=8080"
    environment:
      - DISPLAY=:0
    stdin_open: true
    tty: true
